
//MASTER COPY OF ALL MY FUNCTIONS, CLASSES, AND GLOABL VAR NAMES

abstract class MasterCopy{
//Package: GAME
	//Sub-Package: CHESS
		//Enum: ChessPiece
		//Class: Chess
			//Class:Move
			//Class
		//Class: ChessBoard 
		//Class: King
		//Class: Knight
		//Class: Pawn
		//Class: Queen
		//Class: Pawn
		//Class: Rook
		//Class: Bishop
//Package:GRID 
	//Class: Grid 
	//Class: Square
//Package: PLAYERS // Maybe I need to move this to game class package????
	//Players: 
	//Class: 
//class: Play
}